sudo: false

language: python

addons:
  apt:
    packages:
      - libcups2-dev

python:
  - "3.5"

install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt
  - pip install coveralls
#  - pip install autopep8

script:
  # Run all unit tests
  - coverage run --source=. --omit="*/test*.py" --branch -m unittest discover
  # Check for formatting corresponding to PEP8
#  - autopep=$(autopep8 -dr .); [[ -z $autopep ]];

after_success:
  coveralls
